name: University of Bremen -- Python Tutorials
theme: jekyll-theme-Hacker

markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
    values:
      layout: "default" # Set the default layout
  
use_math: true
